# Configuration for Comparador de Catálogo de Insumos Ebserh
# Renamed repository: comparador-cat-logo-de-insumos

name = "comparador-cat-logo-de-insumos"
main = "worker.ts"
compatibility_date = "2024-03-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
binding = "ASSETS"

